server:
  port: 0
  forward-headers-strategy: framework
spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://postgres:5432/unipeople
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.default_schema: employee
  flyway:
    enabled: true
    schemas: employee
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://api-gateway:18080/auth/.well-known/jwks.json
  cloud:
    openfeign:
      client:
        config:
          organization-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        compression.type: zstd
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
resilience4j:
  circuitbreaker:
    instances:
      orgClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.net.UnknownHostException
          - feign.RetryableException
        ignore-exceptions:
          - feign.FeignException.NotFound
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18761/eureka
    registryFetchIntervalSeconds: 5

kafka:
  topics:
    employee: employee.events