server:
  port: 0
  forward-headers-strategy: framework

spring:
  application:
    name: file-service

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/unipeople
    username: postgres
    password: postgres
    properties:
      schema: file

  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/unipeople
    user: postgres
    password: postgres
    schemas: file
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://api-gateway:18080/auth/.well-known/jwks.json

  kafka:
    bootstrap-servers: kafka:9092   # имя сервиса Kafka в docker-compose (добавишь брокеры)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18761/eureka

s3:
  endpoint: http://minio:9000
  region: us-east-1
  bucket: unipeople-files
  access-key: minio_root
  secret-key: minio_password

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
