server:
  port: 0
  forward-headers-strategy: framework
spring:
  application:
    name: leave-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/unipeople
    username: postgres
    password: postgres
    properties:
      schema: leave
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/unipeople
    user: postgres
    password: postgres
    schemas: leave
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://api-gateway:8080/auth/.well-known/jwks.json
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18761/eureka
