
server:
  port: 0
  forward-headers-strategy: framework
spring:
  application:
    name: leave-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/unipeople
    username: postgres
    password: postgres
    properties:
      schema: leave
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/unipeople
    user: postgres
    password: postgres
    schemas: leave
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://api-gateway:18080/auth/.well-known/jwks.json
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        compression.type: zstd
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18761/eureka
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
kafka:
  topics:
    leave: leave.events