server:
  port: 0

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/unipeople
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.default_schema: duty
  flyway:
    enabled: true
    schemas: duty
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18761/eureka
    registryFetchIntervalSeconds: 5

security:
  jwt:
    issuer: https://auth.unipeople
    audience: unipeople-api
  supervisor:
    username: supervisor
    password: qwerty

management:
  endpoints.web.exposure.include: health,info
